[2022-06-17 18:18:22,225] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: coffee_lake_scrapers-v1.map_images manual__2022-06-17T18:17:32.837310+00:00 [queued]>
[2022-06-17 18:18:22,247] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: coffee_lake_scrapers-v1.map_images manual__2022-06-17T18:17:32.837310+00:00 [queued]>
[2022-06-17 18:18:22,247] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 18:18:22,248] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-17 18:18:22,249] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 18:18:22,276] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): map_images> on 2022-06-17 18:17:32.837310+00:00
[2022-06-17 18:18:22,285] {standard_task_runner.py:52} INFO - Started process 471 to run task
[2022-06-17 18:18:22,289] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'coffee_lake_scrapers-v1', 'map_images', 'manual__2022-06-17T18:17:32.837310+00:00', '--job-id', '201', '--raw', '--subdir', 'DAGS_FOLDER/scraper_dag.py', '--cfg-path', '/tmp/tmpln0yqv47', '--error-file', '/tmp/tmpfhb2gpzn']
[2022-06-17 18:18:22,291] {standard_task_runner.py:80} INFO - Job 201: Subtask map_images
[2022-06-17 18:18:22,403] {task_command.py:370} INFO - Running <TaskInstance: coffee_lake_scrapers-v1.map_images manual__2022-06-17T18:17:32.837310+00:00 [running]> on host 97782298a5be
[2022-06-17 18:18:22,536] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=coffee_lake_scrapers-v1
AIRFLOW_CTX_TASK_ID=map_images
AIRFLOW_CTX_EXECUTION_DATE=2022-06-17T18:17:32.837310+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-17T18:17:32.837310+00:00
[2022-06-17 18:18:23,691] {logging_mixin.py:115} INFO - ['history_changesets', 'history_layers', 'history_nodes', 'history_relations', 'history_ways', 'planet_changesets', 'planet_features', 'planet_features_lines', 'planet_features_multilinestrings', 'planet_features_multipolygons', 'planet_features_other_relations', 'planet_features_points', 'planet_layers', 'planet_nodes', 'planet_relations', 'planet_ways']
[2022-06-17 18:18:27,979] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scraper_dag.py", line 147, in map_images
    img.save(f"{img_path}{row['latitude']}_{row['longitude']}.png")
  File "/home/airflow/.local/lib/python3.7/site-packages/PIL/Image.py", line 2297, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/images/37.560538500_127.035315900.png'
[2022-06-17 18:18:28,000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=coffee_lake_scrapers-v1, task_id=map_images, execution_date=20220617T181732, start_date=20220617T181822, end_date=20220617T181827
[2022-06-17 18:18:28,021] {standard_task_runner.py:97} ERROR - Failed to execute job 201 for task map_images ([Errno 2] No such file or directory: '/opt/airflow/data/images/37.560538500_127.035315900.png'; 471)
[2022-06-17 18:18:28,060] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-17 18:18:28,126] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
