[2022-06-17 14:04:33,541] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: coffee_lake_scrapers-v1.word_count manual__2022-06-17T14:04:15.907307+00:00 [queued]>
[2022-06-17 14:04:33,552] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: coffee_lake_scrapers-v1.word_count manual__2022-06-17T14:04:15.907307+00:00 [queued]>
[2022-06-17 14:04:33,552] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 14:04:33,552] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-17 14:04:33,553] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 14:04:33,565] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): word_count> on 2022-06-17 14:04:15.907307+00:00
[2022-06-17 14:04:33,568] {standard_task_runner.py:52} INFO - Started process 1199 to run task
[2022-06-17 14:04:33,570] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'coffee_lake_scrapers-v1', 'word_count', 'manual__2022-06-17T14:04:15.907307+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/scraper_dag.py', '--cfg-path', '/tmp/tmp80gmxomc', '--error-file', '/tmp/tmpgj7236ts']
[2022-06-17 14:04:33,571] {standard_task_runner.py:80} INFO - Job 74: Subtask word_count
[2022-06-17 14:04:33,611] {task_command.py:370} INFO - Running <TaskInstance: coffee_lake_scrapers-v1.word_count manual__2022-06-17T14:04:15.907307+00:00 [running]> on host 32595384c4c5
[2022-06-17 14:04:33,662] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=coffee_lake_scrapers-v1
AIRFLOW_CTX_TASK_ID=word_count
AIRFLOW_CTX_EXECUTION_DATE=2022-06-17T14:04:15.907307+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-17T14:04:15.907307+00:00
[2022-06-17 14:04:33,665] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scraper_dag.py", line 92, in word_count
    df = pd.DataFrame(file)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 730, in __init__
    raise ValueError("DataFrame constructor not properly called!")
ValueError: DataFrame constructor not properly called!
[2022-06-17 14:04:33,675] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=coffee_lake_scrapers-v1, task_id=word_count, execution_date=20220617T140415, start_date=20220617T140433, end_date=20220617T140433
[2022-06-17 14:04:33,685] {standard_task_runner.py:97} ERROR - Failed to execute job 74 for task word_count (DataFrame constructor not properly called!; 1199)
[2022-06-17 14:04:33,703] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-17 14:04:33,734] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
