[2022-06-17 19:35:19,281] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: coffee_lake_scrapers-v1.upload_imgs manual__2022-06-17T19:34:44.681653+00:00 [queued]>
[2022-06-17 19:35:19,288] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: coffee_lake_scrapers-v1.upload_imgs manual__2022-06-17T19:34:44.681653+00:00 [queued]>
[2022-06-17 19:35:19,289] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 19:35:19,289] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-17 19:35:19,289] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 19:35:19,301] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): upload_imgs> on 2022-06-17 19:34:44.681653+00:00
[2022-06-17 19:35:19,307] {standard_task_runner.py:52} INFO - Started process 3244 to run task
[2022-06-17 19:35:19,310] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'coffee_lake_scrapers-v1', 'upload_imgs', 'manual__2022-06-17T19:34:44.681653+00:00', '--job-id', '323', '--raw', '--subdir', 'DAGS_FOLDER/scraper_dag.py', '--cfg-path', '/tmp/tmpfbvekqh0', '--error-file', '/tmp/tmp8d_m_9q_']
[2022-06-17 19:35:19,311] {standard_task_runner.py:80} INFO - Job 323: Subtask upload_imgs
[2022-06-17 19:35:19,359] {task_command.py:370} INFO - Running <TaskInstance: coffee_lake_scrapers-v1.upload_imgs manual__2022-06-17T19:34:44.681653+00:00 [running]> on host c0a717b7b476
[2022-06-17 19:35:19,416] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=coffee_lake_scrapers-v1
AIRFLOW_CTX_TASK_ID=upload_imgs
AIRFLOW_CTX_EXECUTION_DATE=2022-06-17T19:34:44.681653+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-17T19:34:44.681653+00:00
[2022-06-17 19:35:19,420] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scraper_dag.py", line 169, in upload_imgs
    upload_img_to_gcs(img=outfile, uploaded_filename=outfile)
  File "/opt/airflow/dags/scraper_dag.py", line 198, in upload_img_to_gcs
    client = storage.Client.from_service_account_json(json_credentials_path='/keys/bucket.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 109, in from_service_account_json
    return cls.from_service_account_info(credentials_info, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 76, in from_service_account_info
    credentials = service_account.Credentials.from_service_account_info(info)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/oauth2/service_account.py", line 222, in from_service_account_info
    info, require=["client_email", "token_uri"]
  File "/home/airflow/.local/lib/python3.7/site-packages/google/auth/_service_account_info.py", line 51, in from_dict
    "fields {}.".format(", ".join(missing))
ValueError: Service account info was not in the expected format, missing fields client_email, token_uri.
[2022-06-17 19:35:19,431] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=coffee_lake_scrapers-v1, task_id=upload_imgs, execution_date=20220617T193444, start_date=20220617T193519, end_date=20220617T193519
[2022-06-17 19:35:19,440] {standard_task_runner.py:97} ERROR - Failed to execute job 323 for task upload_imgs (Service account info was not in the expected format, missing fields client_email, token_uri.; 3244)
[2022-06-17 19:35:19,483] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-17 19:35:19,515] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
