[2022-06-17 18:46:03,234] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: coffee_lake_scrapers-v1.word_count manual__2022-06-17T18:45:48.578441+00:00 [queued]>
[2022-06-17 18:46:03,247] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: coffee_lake_scrapers-v1.word_count manual__2022-06-17T18:45:48.578441+00:00 [queued]>
[2022-06-17 18:46:03,247] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 18:46:03,248] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-17 18:46:03,248] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 18:46:03,266] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): word_count> on 2022-06-17 18:45:48.578441+00:00
[2022-06-17 18:46:03,274] {standard_task_runner.py:52} INFO - Started process 249 to run task
[2022-06-17 18:46:03,276] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'coffee_lake_scrapers-v1', 'word_count', 'manual__2022-06-17T18:45:48.578441+00:00', '--job-id', '220', '--raw', '--subdir', 'DAGS_FOLDER/scraper_dag.py', '--cfg-path', '/tmp/tmpxy6106if', '--error-file', '/tmp/tmp5o3yqlsg']
[2022-06-17 18:46:03,277] {standard_task_runner.py:80} INFO - Job 220: Subtask word_count
[2022-06-17 18:46:03,346] {task_command.py:370} INFO - Running <TaskInstance: coffee_lake_scrapers-v1.word_count manual__2022-06-17T18:45:48.578441+00:00 [running]> on host c0a717b7b476
[2022-06-17 18:46:03,465] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=coffee_lake_scrapers-v1
AIRFLOW_CTX_TASK_ID=word_count
AIRFLOW_CTX_EXECUTION_DATE=2022-06-17T18:45:48.578441+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-17T18:45:48.578441+00:00
[2022-06-17 18:46:03,468] {logging_mixin.py:115} INFO - ['images', 'philstar_2022-06-17_05-10-28.csv', 'philstar_2022-06-17_06-15-59.csv', 'philstar_2022-06-17_06-17-43.csv', 'philstar_2022-06-17_06-21-16.csv', 'philstar_2022-06-17_06-45-55.csv']
[2022-06-17 18:46:03,471] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scraper_dag.py", line 92, in word_count
    df = pd.read_csv(outfile)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
IsADirectoryError: [Errno 21] Is a directory: '/opt/airflow/data/images'
[2022-06-17 18:46:03,492] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=coffee_lake_scrapers-v1, task_id=word_count, execution_date=20220617T184548, start_date=20220617T184603, end_date=20220617T184603
[2022-06-17 18:46:03,523] {standard_task_runner.py:97} ERROR - Failed to execute job 220 for task word_count ([Errno 21] Is a directory: '/opt/airflow/data/images'; 249)
[2022-06-17 18:46:03,571] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-17 18:46:03,662] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
