[2022-06-17 14:07:17,855] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: coffee_lake_scrapers-v1.word_count manual__2022-06-17T14:06:59.502074+00:00 [queued]>
[2022-06-17 14:07:17,870] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: coffee_lake_scrapers-v1.word_count manual__2022-06-17T14:06:59.502074+00:00 [queued]>
[2022-06-17 14:07:17,870] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 14:07:17,871] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-17 14:07:17,871] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 14:07:17,890] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): word_count> on 2022-06-17 14:06:59.502074+00:00
[2022-06-17 14:07:17,895] {standard_task_runner.py:52} INFO - Started process 1378 to run task
[2022-06-17 14:07:17,898] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'coffee_lake_scrapers-v1', 'word_count', 'manual__2022-06-17T14:06:59.502074+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/scraper_dag.py', '--cfg-path', '/tmp/tmpzwq6zdrw', '--error-file', '/tmp/tmplaezcvat']
[2022-06-17 14:07:17,899] {standard_task_runner.py:80} INFO - Job 85: Subtask word_count
[2022-06-17 14:07:17,960] {task_command.py:370} INFO - Running <TaskInstance: coffee_lake_scrapers-v1.word_count manual__2022-06-17T14:06:59.502074+00:00 [running]> on host 32595384c4c5
[2022-06-17 14:07:18,038] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=coffee_lake_scrapers-v1
AIRFLOW_CTX_TASK_ID=word_count
AIRFLOW_CTX_EXECUTION_DATE=2022-06-17T14:06:59.502074+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-17T14:06:59.502074+00:00
[2022-06-17 14:07:18,041] {logging_mixin.py:115} INFO - ['inquirer_2022-06-17_01-46-30.csv', 'philstar_2022-06-17_01-48-35.csv', 'philstar_2022-06-17_02-04-26.csv', 'philstar_2022-06-17_02-05-46.csv', 'philstar_2022-06-17_02-07-05.csv']
[2022-06-17 14:07:18,042] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scraper_dag.py", line 93, in word_count
    df = pd.read_csv(file)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'inquirer_2022-06-17_01-46-30.csv'
[2022-06-17 14:07:18,055] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=coffee_lake_scrapers-v1, task_id=word_count, execution_date=20220617T140659, start_date=20220617T140717, end_date=20220617T140718
[2022-06-17 14:07:18,067] {standard_task_runner.py:97} ERROR - Failed to execute job 85 for task word_count ([Errno 2] No such file or directory: 'inquirer_2022-06-17_01-46-30.csv'; 1378)
[2022-06-17 14:07:18,112] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-17 14:07:18,160] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
