[2022-06-17 20:25:01,087] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: coffee_lake_scrapers-v1.upload_imgs manual__2022-06-17T20:24:23.050847+00:00 [queued]>
[2022-06-17 20:25:01,096] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: coffee_lake_scrapers-v1.upload_imgs manual__2022-06-17T20:24:23.050847+00:00 [queued]>
[2022-06-17 20:25:01,097] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 20:25:01,097] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-17 20:25:01,097] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-17 20:25:01,108] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): upload_imgs> on 2022-06-17 20:24:23.050847+00:00
[2022-06-17 20:25:01,118] {standard_task_runner.py:52} INFO - Started process 601 to run task
[2022-06-17 20:25:01,122] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'coffee_lake_scrapers-v1', 'upload_imgs', 'manual__2022-06-17T20:24:23.050847+00:00', '--job-id', '375', '--raw', '--subdir', 'DAGS_FOLDER/scraper_dag.py', '--cfg-path', '/tmp/tmpp62t5m29', '--error-file', '/tmp/tmp3f8q4qhg']
[2022-06-17 20:25:01,123] {standard_task_runner.py:80} INFO - Job 375: Subtask upload_imgs
[2022-06-17 20:25:01,164] {task_command.py:370} INFO - Running <TaskInstance: coffee_lake_scrapers-v1.upload_imgs manual__2022-06-17T20:24:23.050847+00:00 [running]> on host 99f2822d4305
[2022-06-17 20:25:01,219] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=coffee_lake_scrapers-v1
AIRFLOW_CTX_TASK_ID=upload_imgs
AIRFLOW_CTX_EXECUTION_DATE=2022-06-17T20:24:23.050847+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-17T20:24:23.050847+00:00
[2022-06-17 20:25:01,524] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scraper_dag.py", line 171, in upload_imgs
    upload_img_to_gcs(img=img, uploaded_filename=outfile)
  File "/opt/airflow/dags/scraper_dag.py", line 207, in upload_img_to_gcs
    gcs_resource.Object(BUCKET_NAME, MY_FOLDER_PREFIX + "/" + uploaded_filename).put(Body=img)
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/resources/factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 879, in _make_api_call
    api_params, operation_model, context=request_context
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 940, in _convert_to_request_dict
    api_params, operation_model
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Body, value: None, type: <class 'NoneType'>, valid types: <class 'bytes'>, <class 'bytearray'>, file-like object
[2022-06-17 20:25:01,535] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=coffee_lake_scrapers-v1, task_id=upload_imgs, execution_date=20220617T202423, start_date=20220617T202501, end_date=20220617T202501
[2022-06-17 20:25:01,544] {standard_task_runner.py:97} ERROR - Failed to execute job 375 for task upload_imgs (Parameter validation failed:
Invalid type for parameter Body, value: None, type: <class 'NoneType'>, valid types: <class 'bytes'>, <class 'bytearray'>, file-like object; 601)
[2022-06-17 20:25:01,576] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-17 20:25:01,609] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
