[2022-06-18 06:52:51,974] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: coffee_lake_demo-v2.spacy_ner manual__2022-06-18T06:52:30.500581+00:00 [queued]>
[2022-06-18 06:52:51,993] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: coffee_lake_demo-v2.spacy_ner manual__2022-06-18T06:52:30.500581+00:00 [queued]>
[2022-06-18 06:52:51,994] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-18 06:52:51,995] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-18 06:52:51,995] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-18 06:52:52,019] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): spacy_ner> on 2022-06-18 06:52:30.500581+00:00
[2022-06-18 06:52:52,027] {standard_task_runner.py:52} INFO - Started process 295 to run task
[2022-06-18 06:52:52,030] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'coffee_lake_demo-v2', 'spacy_ner', 'manual__2022-06-18T06:52:30.500581+00:00', '--job-id', '498', '--raw', '--subdir', 'DAGS_FOLDER/scraper_v2_dag.py', '--cfg-path', '/tmp/tmp35c93jx0', '--error-file', '/tmp/tmpylwcmkr9']
[2022-06-18 06:52:52,031] {standard_task_runner.py:80} INFO - Job 498: Subtask spacy_ner
[2022-06-18 06:52:52,100] {task_command.py:370} INFO - Running <TaskInstance: coffee_lake_demo-v2.spacy_ner manual__2022-06-18T06:52:30.500581+00:00 [running]> on host 312614bad459
[2022-06-18 06:52:52,209] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=coffee_lake_demo-v2
AIRFLOW_CTX_TASK_ID=spacy_ner
AIRFLOW_CTX_EXECUTION_DATE=2022-06-18T06:52:30.500581+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-18T06:52:30.500581+00:00
[2022-06-18 06:52:52,254] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/spacy/util.py:845: UserWarning: [W094] Model 'en_core_web_sm' (2.2.5) specifies an under-constrained spaCy version requirement: >=2.2.2. This can lead to compatibility problems with older versions, or as new spaCy versions are released, because the model may say it's compatible when it's not. Consider changing the "spacy_version" in your meta.json to a version range, with a lower and upper pin. For example: >=3.3.1,<3.4.0
  warnings.warn(warn_msg)

[2022-06-18 06:52:52,256] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scraper_v2_dag.py", line 139, in spacy_ner
    nlp = spacy.load("/model/en_core_web_sm/en_core_web_sm-2.2.5")
  File "/home/airflow/.local/lib/python3.7/site-packages/spacy/__init__.py", line 52, in load
    name, vocab=vocab, disable=disable, exclude=exclude, config=config
  File "/home/airflow/.local/lib/python3.7/site-packages/spacy/util.py", line 422, in load_model
    return load_model_from_path(Path(name), **kwargs)  # type: ignore[arg-type]
  File "/home/airflow/.local/lib/python3.7/site-packages/spacy/util.py", line 487, in load_model_from_path
    config = load_config(config_path, overrides=overrides)
  File "/home/airflow/.local/lib/python3.7/site-packages/spacy/util.py", line 650, in load_config
    raise IOError(Errors.E053.format(path=config_path, name="config file"))
OSError: [E053] Could not read config file from /model/en_core_web_sm/en_core_web_sm-2.2.5/config.cfg
[2022-06-18 06:52:52,271] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=coffee_lake_demo-v2, task_id=spacy_ner, execution_date=20220618T065230, start_date=20220618T065251, end_date=20220618T065252
[2022-06-18 06:52:52,287] {standard_task_runner.py:97} ERROR - Failed to execute job 498 for task spacy_ner ([E053] Could not read config file from /model/en_core_web_sm/en_core_web_sm-2.2.5/config.cfg; 295)
[2022-06-18 06:52:52,324] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-18 06:52:52,386] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
